language:
    python
python:
    - "2.7"
install:
    "pip install coveralls -r requirements.txt"
branches:
    only:
        - master
script:
    - export PYTHONPATH=${PYTHONPATH}:$(pwd)
    - coverage run --branch --source oppy $(which trial) oppy
after_success:
    - coveralls
